version: '3.2'

services:
    notificaion_redis:
      container_name: 'notificaion_redis'
      image: redis:alpine
      ports:
        - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
      restart: always

    notification_app:
      container_name: 'notification'
      build: .
      links:
        - "notificaion_redis"
      depends_on:
        - "notificaion_redis"
      restart: always

    notification_rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      environment:
        - RABBITMQ_DEFAULT_USER=${RMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RMQ_DEFAULT_PASSWORD}
      ports:
          - ${RMQ_EXTERNAL_PORT}:${RMQ_PORT}
          - ${RMQ_MANAGMENT_EXTERNAL_PORT}:${RMQ_MANAGMENT_PORT}
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
          - rabbitmq_go_net

  networks:
    rabbitmq_go_net:
      driver: bridge